"""SQLAlchemy table definitions — the physical schema, and nothing else.

Infrastructure, so it lives here rather than in `core/`: the repository Protocol
the handler depends on is domain, its Postgres implementation and these tables
are not. Named `tables` rather than `models` because "model" is the vaguest
word available for a file whose whole job is the physical schema — and the
Pydantic types on the wire, which would be the other claimant, are `frames`.

Alembic's `env.py` imports `metadata` from here and nothing else, so autogenerate
sees the schema without importing the API.
"""

from enum import StrEnum

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Identity,
    Index,
    MetaData,
    Table,
    Text,
    UniqueConstraint,
    Uuid,
    func,
    text,
)

from core.repository import Role, Status

# Explicit constraint naming, set before any table is defined.
#
# Without this Postgres invents names, and they are only mostly predictable — an
# autogenerated downgrade then emits `drop constraint` for a name that may not
# match what was actually created, which fails at the worst possible moment.
# Fixing the convention now costs nothing; adopting it after tables exist means
# renaming every constraint in a migration.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


def _quoted(values: type[StrEnum]) -> str:
    """`'a', 'b'` — a SQL literal list, for an `in (...)` check constraint."""
    return ", ".join(f"'{v}'" for v in values)


chat_sessions = Table(
    "chat_sessions",
    metadata,
    # The canonical uuid from the URL path, not a surrogate. api/chat.py refuses
    # every non-canonical spelling of a uuid precisely so this key is unambiguous.
    Column("id", Uuid(), primary_key=True),
    # The per-session seq allocator. A Postgres sequence is the wrong tool here:
    # it is global rather than per-session, and rollbacks burn values — exactly
    # the gap the contract forbids. UPDATE … RETURNING on this column takes a row
    # lock, so concurrent turns serialize, and a rolled-back turn consumes nothing.
    Column("next_seq", BigInteger, nullable=False, server_default=text("1")),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("last_seen_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)


chat_messages = Table(
    "chat_messages",
    metadata,
    # Internal key, sequential. message_id is uuid4 and therefore random, so
    # using it as the primary key scatters inserts across the index and fragments
    # it as this table grows. The exposed identity stays opaque; the physical one
    # stays ordered.
    Column("id", BigInteger, Identity(always=True), primary_key=True),
    Column(
        "session_id",
        Uuid(),
        ForeignKey("chat_sessions.id", ondelete="CASCADE"),
        nullable=False,
    ),
    # Gap-free per session, allocated from chat_sessions.next_seq at insert.
    Column("seq", BigInteger, nullable=False),
    # The wire identity, server-minted, carried by ack / delta / done.
    Column("message_id", Uuid(), nullable=False, unique=True),
    Column("role", Text, nullable=False),
    Column("status", Text, nullable=False),
    # Accumulated as deltas arrive, final at `done`. Deltas are never stored
    # per-chunk: a chunk is a rendering detail, not a durable fact, so resume
    # replays completed messages rather than re-streaming tokens.
    Column("text", Text, nullable=False, server_default=text("''")),
    # The client's idempotency key. User rows only — see the check below.
    Column("client_msg_id", Text),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("completed_at", DateTime(timezone=True)),
    # Text plus a check rather than a Postgres enum: adding a state later is then
    # a constraint change instead of a type migration.
    #
    # Spelled from core.repository's enums so there is one list, not two. Note
    # what this does *not* buy: alembic autogenerate cannot see a CHECK
    # constraint change, so editing an enum still produces an empty migration
    # and the database keeps rejecting the new value until someone hand-writes
    # the drop/create. See alembic/README.
    CheckConstraint(f"role in ({_quoted(Role)})", name="role"),
    CheckConstraint(f"status in ({_quoted(Status)})", name="status"),
    # Ties the idempotency key to the role in both directions. Without it the
    # partial unique index below silently permits an assistant row to carry a
    # client's key, and a user row to carry none — which would make the re-ack
    # path unreachable for that message.
    CheckConstraint(
        f"(role = '{Role.USER}') = (client_msg_id is not null)",
        name="client_msg_id_matches_role",
    ),
    # Enforces gap-free allocation at the database rather than trusting the
    # application, and is the index the resume scan wants: equality column first,
    # range column second, for `where session_id = $1 and seq > $2 order by seq`.
    # Being leftmost on session_id, it is also the required index on the FK.
    UniqueConstraint("session_id", "seq"),
)

# Partial, not a plain unique constraint: assistant rows always have a NULL key,
# and there is no reason to carry them in this index at all. Named explicitly
# because the `ix` convention would prefix a unique index with `ix_`.
Index(
    "uq_chat_messages_session_id_client_msg_id",
    chat_messages.c.session_id,
    chat_messages.c.client_msg_id,
    unique=True,
    postgresql_where=chat_messages.c.client_msg_id.isnot(None),
)
