"""SQLAlchemy table definitions — the physical schema, and nothing else.

Infrastructure, so it lives here rather than in `core/`: the repository Protocol
the handler depends on is domain, its Postgres implementation and these tables
are not. Named `tables` rather than `models` because "model" is the vaguest
word available for a file whose whole job is the physical schema — and the
Pydantic types on the wire, which would be the other claimant, are `frames`.

Alembic's `env.py` imports `metadata` from here and nothing else, so autogenerate
sees the schema without importing the API.
"""

from enum import StrEnum

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Identity,
    Index,
    Integer,
    MetaData,
    Table,
    Text,
    UniqueConstraint,
    Uuid,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB

from core.chat_repository import Role, Status
from core.jobs import JobState

# Explicit constraint naming, set before any table is defined.
#
# Without this Postgres invents names, and they are only mostly predictable — an
# autogenerated downgrade then emits `drop constraint` for a name that may not
# match what was actually created, which fails at the worst possible moment.
# Fixing the convention now costs nothing; adopting it after tables exist means
# renaming every constraint in a migration.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


def _quoted(values: type[StrEnum]) -> str:
    """`'a', 'b'` — a SQL literal list, for an `in (...)` check constraint."""
    return ", ".join(f"'{v}'" for v in values)


chat_sessions = Table(
    "chat_sessions",
    metadata,
    # The canonical uuid from the URL path, not a surrogate. api/chat.py refuses
    # every non-canonical spelling of a uuid precisely so this key is unambiguous.
    Column("id", Uuid(), primary_key=True),
    # The per-session seq allocator. A Postgres sequence is the wrong tool here:
    # it is global rather than per-session, and rollbacks burn values — exactly
    # the gap the contract forbids. UPDATE … RETURNING on this column takes a row
    # lock, so concurrent turns serialize, and a rolled-back turn consumes nothing.
    Column("next_seq", BigInteger, nullable=False, server_default=text("1")),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("last_seen_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)


chat_messages = Table(
    "chat_messages",
    metadata,
    # Internal key, sequential. message_id is uuid4 and therefore random, so
    # using it as the primary key scatters inserts across the index and fragments
    # it as this table grows. The exposed identity stays opaque; the physical one
    # stays ordered.
    Column("id", BigInteger, Identity(always=True), primary_key=True),
    Column(
        "session_id",
        Uuid(),
        ForeignKey("chat_sessions.id", ondelete="CASCADE"),
        nullable=False,
    ),
    # Gap-free per session, allocated from chat_sessions.next_seq at insert.
    Column("seq", BigInteger, nullable=False),
    # The wire identity, server-minted, carried by ack / delta / done.
    Column("message_id", Uuid(), nullable=False, unique=True),
    Column("role", Text, nullable=False),
    Column("status", Text, nullable=False),
    # Accumulated as deltas arrive, final at `done`. Deltas are never stored
    # per-chunk: a chunk is a rendering detail, not a durable fact, so resume
    # replays completed messages rather than re-streaming tokens.
    Column("text", Text, nullable=False, server_default=text("''")),
    # The client's idempotency key. User rows only — see the check below.
    Column("client_msg_id", Text),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("completed_at", DateTime(timezone=True)),
    # Text plus a check rather than a Postgres enum: adding a state later is then
    # a constraint change instead of a type migration.
    #
    # Spelled from core.chat_repository's enums so there is one list, not two. Note
    # what this does *not* buy: alembic autogenerate cannot see a CHECK
    # constraint change, so editing an enum still produces an empty migration
    # and the database keeps rejecting the new value until someone hand-writes
    # the drop/create. See alembic/README.
    CheckConstraint(f"role in ({_quoted(Role)})", name="role"),
    CheckConstraint(f"status in ({_quoted(Status)})", name="status"),
    # Ties the idempotency key to the role in both directions. Without it the
    # partial unique index below silently permits an assistant row to carry a
    # client's key, and a user row to carry none — which would make the re-ack
    # path unreachable for that message.
    CheckConstraint(
        f"(role = '{Role.USER}') = (client_msg_id is not null)",
        name="client_msg_id_matches_role",
    ),
    # Enforces gap-free allocation at the database rather than trusting the
    # application, and is the index the resume scan wants: equality column first,
    # range column second, for `where session_id = $1 and seq > $2 order by seq`.
    # Being leftmost on session_id, it is also the required index on the FK.
    UniqueConstraint("session_id", "seq"),
)

# Partial, not a plain unique constraint: assistant rows always have a NULL key,
# and there is no reason to carry them in this index at all. Named explicitly
# because the `ix` convention would prefix a unique index with `ix_`.
Index(
    "uq_chat_messages_session_id_client_msg_id",
    chat_messages.c.session_id,
    chat_messages.c.client_msg_id,
    unique=True,
    postgresql_where=chat_messages.c.client_msg_id.isnot(None),
)


jobs = Table(
    "jobs",
    metadata,
    # The wire identity, and the physical key. Unlike chat_messages this table
    # has no surrogate: a job is addressed by uuid from the moment it is created
    # — a client watches one, a worker leases one — so a second identity would
    # be a column nothing ever reads. The index fragmentation that argument
    # avoided there is not a concern here: jobs are minutes apart, not tokens.
    Column("id", Uuid(), primary_key=True),
    # Nullable, because a job need not have come from a conversation — a
    # scheduled backfill has none — and because the queue must not require the
    # chat schema to be useful. CASCADE matches chat_messages: deleting a
    # session takes its jobs with it.
    Column(
        "session_id",
        Uuid(),
        ForeignKey("chat_sessions.id", ondelete="CASCADE"),
    ),
    # The caller's deduplication key. `client_msg_id`'s counterpart, and NOT
    # NULL unlike it: every job has one, defaulted client-side to a fresh uuid,
    # so there is no partial-index trick to play here.
    Column("idempotency_key", Text, nullable=False),
    # Which analysis, and its AnalysisRequest. Both opaque to the queue, which
    # is what keeps this table reusable for work unrelated to analytics.
    Column("kind", Text, nullable=False),
    Column("payload", JSONB, nullable=False),
    Column("state", Text, nullable=False, server_default=text(f"'{JobState.QUEUED}'")),
    Column("attempts", Integer, nullable=False, server_default=text("0")),
    Column("max_attempts", Integer, nullable=False, server_default=text("3")),
    # Backoff, and the only scheduling mechanism this queue has. A job is
    # invisible to `reserve` until now() passes it, which is how `nack(retry_in)`
    # holds a failure back without a timer anywhere in the application.
    Column("run_after", DateTime(timezone=True), nullable=False, server_default=func.now()),
    # RabbitMQ only: set after basic_publish returns. Null on a committed job
    # means the publish never happened, which is the one dual-write failure that
    # can actually lose work — see docs/jobs.md. The Postgres implementation
    # never reads or writes it: its insert *is* the publish.
    Column("published_at", DateTime(timezone=True)),
    # The fencing token, new on every reservation. A consumer that stalls past
    # its deadline and wakes after another has claimed the job presents a token
    # the row no longer holds, and its ack is refused instead of overwriting a
    # result someone else recorded.
    Column("lease_id", Uuid()),
    # The lease is a timestamp, never a held lock: nothing is blocked while a
    # consumer works, and the claim lapses on its own if that consumer dies.
    # That is what lets a five-minute solve outlive the process running it.
    Column("lease_expires_at", DateTime(timezone=True)),
    # Observability only. Correctness rests on lease_id, never on this.
    Column("lease_owner", Text),
    # Asked for from outside; noticed by the consumer between units of work.
    # Nothing here can stop a process already inside a computation.
    Column("cancel_requested", Boolean, nullable=False, server_default=text("false")),
    # The object-storage key. Phase 3 sets it; until then nothing does.
    Column("result_ref", Text),
    Column("error", Text),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    # Same reasoning as chat_messages: text plus a check, so adding a state is a
    # constraint change rather than a type migration — and the same trap, that
    # autogenerate cannot see a CHECK change and will emit an empty migration.
    CheckConstraint(f"state in ({_quoted(JobState)})", name="state"),
    # A lease is all-or-nothing. Half of one — an id with no deadline — would
    # let `reserve` treat a live claim as expired, or never expire a dead one.
    CheckConstraint(
        "(lease_id is null) = (lease_expires_at is null)",
        name="lease_is_whole",
    ),
    CheckConstraint("attempts >= 0 and max_attempts > 0", name="attempts_sane"),
    # The idempotency key, scoped to the session. Two clients that both call
    # their message "1" are not submitting the same job.
    #
    # NULLS NOT DISTINCT because session_id is nullable and the default would
    # make every session-less job unique regardless of its key — silently
    # disabling deduplication for exactly the callers (backfills, retries from
    # a script) most likely to submit the same work twice.
    UniqueConstraint(
        "session_id",
        "idempotency_key",
        name="uq_jobs_session_id_idempotency_key",
        postgresql_nulls_not_distinct=True,
    ),
)

# The claim query's index: equality on the state, then the columns it orders by.
# Partial, because `reserve` looks only at work that is waiting — a table that
# is mostly finished jobs should not carry them here. `failed` is included
# because a job awaiting retry is reservable once its run_after passes; `running`
# is not, since an expired lease is found by the second index below.
Index(
    "ix_jobs_reservable",
    jobs.c.run_after,
    jobs.c.created_at,
    postgresql_where=jobs.c.state.in_([JobState.QUEUED, JobState.FAILED]),
)

# Expiry is a predicate, not a sweeper (docs/jobs.md), so the claim query also
# scans for lapsed leases. Separate and partial rather than folded into the
# index above: the two halves have disjoint predicates and different sort keys,
# and one combined index would serve neither.
Index(
    "ix_jobs_expired_leases",
    jobs.c.lease_expires_at,
    postgresql_where=jobs.c.state == JobState.RUNNING,
)

# The orphan sweep: jobs committed but never published. Tiny — it holds only the
# rows currently in flight between the insert and the publish, which is normally
# none of them. That is precisely why it is worth having: the query runs on a
# timer forever and should touch nothing.
Index(
    "ix_jobs_unpublished",
    jobs.c.created_at,
    postgresql_where=jobs.c.published_at.is_(None),
)
