"""jobs table

Revision ID: d65c158b518a
Revises: 27cae6e6a044
Create Date: 2026-08-20 14:59:47.748879

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d65c158b518a"
down_revision: str | None = "27cae6e6a044"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'queued'"), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_id", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.Text(), nullable=True),
        sa.Column(
            "cancel_requested", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("result_ref", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state in ('queued', 'running', 'done', 'failed', 'dead', 'cancelled')",
            name=op.f("ck_jobs_state"),
        ),
        sa.CheckConstraint(
            "(lease_id is null) = (lease_expires_at is null)", name=op.f("ck_jobs_lease_is_whole")
        ),
        sa.CheckConstraint(
            "attempts >= 0 and max_attempts > 0", name=op.f("ck_jobs_attempts_sane")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
            name=op.f("fk_jobs_session_id_chat_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint(
            "session_id",
            "idempotency_key",
            name="uq_jobs_session_id_idempotency_key",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_jobs_expired_leases",
        "jobs",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("state = 'running'"),
    )
    op.create_index(
        "ix_jobs_reservable",
        "jobs",
        ["run_after", "created_at"],
        unique=False,
        postgresql_where=sa.text("state IN ('queued', 'failed')"),
    )
    op.create_index(
        "ix_jobs_unpublished",
        "jobs",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_jobs_unpublished", table_name="jobs", postgresql_where=sa.text("published_at IS NULL")
    )
    op.drop_index(
        "ix_jobs_reservable",
        table_name="jobs",
        postgresql_where=sa.text("state IN ('queued', 'failed')"),
    )
    op.drop_index(
        "ix_jobs_expired_leases", table_name="jobs", postgresql_where=sa.text("state = 'running'")
    )
    op.drop_table("jobs")
    # ### end Alembic commands ###
