"""chat_sessions and chat_messages

Revision ID: 27cae6e6a044
Revises:
Create Date: 2026-08-17 16:43:37.173754

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27cae6e6a044"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("next_seq", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_sessions")),
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("client_msg_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(role = 'user') = (client_msg_id is not null)",
            name=op.f("ck_chat_messages_client_msg_id_matches_role"),
        ),
        sa.CheckConstraint("role in ('user', 'assistant')", name=op.f("ck_chat_messages_role")),
        sa.CheckConstraint(
            "status in ('streaming', 'complete', 'failed')", name=op.f("ck_chat_messages_status")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
            name=op.f("fk_chat_messages_session_id_chat_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
        sa.UniqueConstraint("message_id", name=op.f("uq_chat_messages_message_id")),
        sa.UniqueConstraint("session_id", "seq", name=op.f("uq_chat_messages_session_id_seq")),
    )
    op.create_index(
        "uq_chat_messages_session_id_client_msg_id",
        "chat_messages",
        ["session_id", "client_msg_id"],
        unique=True,
        postgresql_where=sa.text("client_msg_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_chat_messages_session_id_client_msg_id",
        table_name="chat_messages",
        postgresql_where=sa.text("client_msg_id IS NOT NULL"),
    )
    op.drop_table("chat_messages")
    op.drop_table("chat_sessions")
    # ### end Alembic commands ###
